dist: trusty
sudo: false

language: go
go:
  - 1.14.x
  - 1.15.x

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go install golang.org/x/tools/cmd/goyacc

script:
  - set -e
  - echo "" > coverage.txt
  - |
    for d in $(go list ./... | grep -v vendor); do
        go test -race -coverprofile=profile.out -covermode=atomic $d
        if [ -f profile.out ]; then
            cat profile.out >> coverage.txt
            rm profile.out
        fi
    done

after_success:
  - bash <(curl -s https://codecov.io/bash)
