dist: trusty
sudo: false

language: go
go:
  - 1.14.x
  - 1.15.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go install golang.org/x/tools/cmd/goyacc

script:
  - travis_retry $HOME/gopath/bin/goveralls -service=travis-ci
